server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/jtsys?serverTimezone=GMT
    username: root
    password: 123
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/sys/*.xml
logging:
  level:
    com.lala: debug
