server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

spring:
  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3308/jtsys?serverTimezone=GMT
      username: root
      password: 123

    second:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3308/bishi?serverTimezone=GMT
      username: root
      password: 123

  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    com.lala: debug

jwt:
  config:
    key: lala
    ttl: 120